/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.tjumyk;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 *
 * @author E40-G8C
 */
// Generated by JFXTableClassBuilder
// Inputs:
// id,String
// name,String
// End
public class ClassTableRecord {

    StringProperty id;
    StringProperty name;

    public ClassTableRecord(String id, String name) {
        setId(id);
        setName(name);
    }

    public StringProperty idProperty() {
        if (id == null) {
            id = new SimpleStringProperty();
        }
        return id;
    }

    public String getId() {
        return idProperty().get();
    }

    public void setId(String value) {
        idProperty().set(value);
    }

    public StringProperty nameProperty() {
        if (name == null) {
            name = new SimpleStringProperty();
        }
        return name;
    }

    public String getName() {
        return nameProperty().get();
    }

    public void setName(String value) {
        nameProperty().set(value);
    }
// Code Example of building corresponding TableColumns:
//
// TableColumnBuilder.create().text("id").cellValueFactory(new PropertyValueFactory("id")).prefWidth(200).build(),
// TableColumnBuilder.create().text("name").cellValueFactory(new PropertyValueFactory("name")).prefWidth(200).build()
}