/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.tjumyk;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 *
 * @author E40-G8C
 */
// Generated by JFXTableClassBuilder
// Inputs:
// sid,String
// sname,String
// cid,Integer
// cname,String
// year,Integer
// score,Integer
// End
public class TakeCourseTableRecord {

    StringProperty sid;
    StringProperty sname;
    IntegerProperty cid;
    StringProperty cname;
    IntegerProperty year;
    IntegerProperty score;

    public TakeCourseTableRecord(String sid, String sname, Integer cid, String cname, Integer year,
            Integer score) {
        setSid(sid);
        setSname(sname);
        setCid(cid);
        setCname(cname);
        setYear(year);
        setScore(score);
    }

    public StringProperty sidProperty() {
        if (sid == null) {
            sid = new SimpleStringProperty();
        }
        return sid;
    }

    public String getSid() {
        return sidProperty().get();
    }

    public void setSid(String value) {
        sidProperty().set(value);
    }

    public StringProperty snameProperty() {
        if (sname == null) {
            sname = new SimpleStringProperty();
        }
        return sname;
    }

    public String getSname() {
        return snameProperty().get();
    }

    public void setSname(String value) {
        snameProperty().set(value);
    }

    public IntegerProperty cidProperty() {
        if (cid == null) {
            cid = new SimpleIntegerProperty();
        }
        return cid;
    }

    public Integer getCid() {
        return cidProperty().get();
    }

    public void setCid(Integer value) {
        cidProperty().set(value);
    }

    public StringProperty cnameProperty() {
        if (cname == null) {
            cname = new SimpleStringProperty();
        }
        return cname;
    }

    public String getCname() {
        return cnameProperty().get();
    }

    public void setCname(String value) {
        cnameProperty().set(value);
    }

    public IntegerProperty yearProperty() {
        if (year == null) {
            year = new SimpleIntegerProperty();
        }
        return year;
    }

    public Integer getYear() {
        return yearProperty().get();
    }

    public void setYear(Integer value) {
        yearProperty().set(value);
    }

    public IntegerProperty scoreProperty() {
        if (score == null) {
            score = new SimpleIntegerProperty();
        }
        return score;
    }

    public Integer getScore() {
        return scoreProperty().get();
    }

    public void setScore(Integer value) {
        scoreProperty().set(value);
    }
// Code Example of building corresponding TableColumns:
//
// TableColumnBuilder.create().text("sid").cellValueFactory(new PropertyValueFactory("sid")).prefWidth(200).build(),
// TableColumnBuilder.create().text("sname").cellValueFactory(new PropertyValueFactory("sname")).prefWidth(200).build(),
// TableColumnBuilder.create().text("cid").cellValueFactory(new PropertyValueFactory("cid")).prefWidth(200).build(),
// TableColumnBuilder.create().text("cname").cellValueFactory(new PropertyValueFactory("cname")).prefWidth(200).build(),
// TableColumnBuilder.create().text("year").cellValueFactory(new PropertyValueFactory("year")).prefWidth(200).build(),
// TableColumnBuilder.create().text("score").cellValueFactory(new PropertyValueFactory("score")).prefWidth(200).build()
}
